name: Docker CI
on:
  push:
    branches: [ "main" ]

env:
  dockerimage_tag: ${{ github.sha }}
  dockerimage_name: yourzinc/lab2
  config_repo: yourzinc/lab2-config
  config_repo_path: lab2-config
  mode: dev

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          path: homepage
          
      - name: Generate Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ env.dockerimage_name }}
          tags: |
            ${{ env.dockerimage_tag }}
            latest
          flavor: |
            latest=true
          
      - name: Yarn Setup
        uses: DerYeger/yarn-setup-action@v1.0.1
        with:
          node-version: 18
          
      - name: Yarn Build
        run: |
          yarn
          yarn build
            
      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v2.1.0
        
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2.5.0

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: yourzinc
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v4.0.0
        with:
          context: .
          platforms: linux/amd64,linux/arm64/v8
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: false
      
      - name: Setup Kustomize
        uses: imranismail/setup-kustomize@v2.0.0

      - name: Checkout for Operation repository
        uses: actions/checkout@v3
        with:
          repository: ${{ env.config_repo }}
          ref: main  
          token: ${{ secrets.ACTION_TOKEN }}
          path: ${{ env.config_repo_path }}

      - name: Update Kubernetes resources
        run: |
          cd ${{ env.config_repo_path }}/overlays/${{ env.mode }}/
          kustomize edit set image ${{ env.dockerimage_name }}:${{ env.dockerimage_tag }}
          cat kustomization.yaml

      - name: Commit minifest files
        run: |
          cd ${{ env.config_repo_path }}
          git config --global user.email "your.zinc@gmail.com"
          git config --global user.name "yourzinc"
          git commit -am "feat: container image tag updated"
          git push -u origin main